[package]
edition = "2024"
name    = "vprog-tictactoe-node"
publish = false
version = "0.1.0"

[[bin]]
name = "ttd"
path = "src/main.rs"

[features]
cuda = ["vprogs-runner/cuda"]

[dependencies]
ctrlc                       = { workspace = true }
kaspa-consensus-core        = { workspace = true }
kaspa-core                  = { workspace = true }
kaspa-hashes                = { workspace = true }
log                         = { workspace = true }
secp256k1                   = { workspace = true }
tokio                       = { workspace = true }
vprogs-runner               = { workspace = true }
vprogs-zk-backend-risc0-api = { workspace = true }
