[package]
edition = "2024"
name    = "vprog-tictactoe-driver"
publish = false
version = "0.1.0"

[lib]
name = "vprog_tictactoe_driver"
path = "src/lib.rs"

[[bin]]
name = "ttflow"
path = "src/main.rs"

[dependencies]
ctrlc                           = { workspace = true }
kaspa-addresses                 = { workspace = true }
kaspa-consensus-core            = { workspace = true }
kaspa-core                      = { workspace = true }
kaspa-hashes                    = { workspace = true }
kaspa-rpc-core                  = { workspace = true }
kaspa-txscript                  = { workspace = true }
kaspa-wrpc-client               = { workspace = true }
log                             = { workspace = true }
secp256k1                       = { workspace = true }
tokio                           = { workspace = true }
vprog-tictactoe-guest           = { path = "../guest" }
vprogs-core-types               = { workspace = true }
vprogs-l1-wallet                = { workspace = true }
vprogs-zk-abi                   = { workspace = true }
vprogs-zk-backend-risc0-api     = { workspace = true }
vprogs-zk-backend-risc0-app-kit = { workspace = true }

[dev-dependencies]
axum                               = { workspace = true }
borsh                              = { workspace = true }
kaspa-grpc-client                  = { git = "https://github.com/kaspanet/rusty-kaspa", branch = "master" }
kaspa-testing-integration          = { git = "https://github.com/kaspanet/rusty-kaspa", branch = "master" }
kaspad                             = { git = "https://github.com/kaspanet/rusty-kaspa", branch = "master" }
serde_json                         = { workspace = true }
tempfile                           = "3"
vprog-tictactoe-encoder-wasm       = { path = "../encoder-wasm" }
vprog-tictactoe-node               = { path = "../node" }
vprogs-node-test-utils             = { workspace = true }
vprogs-runner                      = { workspace = true }
vprogs-scheduling-scheduler        = { workspace = true }
vprogs-storage-canonical-chain     = { workspace = true }
vprogs-storage-types               = { workspace = true }
vprogs-zk-backend-risc0-test-suite = { workspace = true }
